# https://thecodersblog.com/deploying-static-website-surge-github-actions
# https://surge.sh/
# https://vitepress.dev/guide/deploy#surge
# https://github.com/joaopalmeiro/jupyterlab-icons-viewer#deployment-surge
# https://github.com/yavisht/deploy-via-surge.sh-github-action-template
# https://github.com/yavisht/deploy-via-surge.sh-github-action-template/blob/master/.github/workflows/deployment.yml
# https://vitepress.dev/guide/deploy#github-pages
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

name: Deploy documentation to Surge

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm install
      - run: npm run docs:build
      - run: npm install --global surge
      - run: surge docs/.vitepress/dist https://d3-extra-scale-chromatic.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
